kind = "web"
previewPath = "/"
title = "Wédas"
version = "1.0.0"
id = "artifacts/wedas"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22361

[services.development]
run = "pnpm --filter @workspace/wedas run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wedas", "run", "build" ]
publicDir = "artifacts/wedas/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22361"
BASE_PATH = "/"
